version: '3.8'

services:
  mtl-food-api:
    build: ./api
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8765", "--reload"] 
    volumes:
      - ./api:/api
    ports:
      - "8765:8765"
  mtl-food-web:
    build: ./web
    ports:
      - '5678:80'